name: jax-fem-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.12
  - numpy==2.3.0
  - scipy==1.15.2
  - matplotlib==3.10.3
  - meshio==5.3.5
  - petsc4py==3.23.3
  - fenics==2019.1.0
  - gmsh==4.13.1
  - python-gmsh==4.13.1
  - pip
  - pip:
    - setuptools
    - wheel
    - fenics-basix==0.9.0
    - pyfiglet==1.0.3
    - jax[cpu]==0.5.3
    - jax-fem==0.0.9